# Bill
# https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#about-billing-for-github-actions
# work run time: each workflow run is limited 72 hours
# job queue time: limited 24 hours
# Api requests: execute up to 1000 API
# job matrix: can generate a maximum of 256 jobs per workflow run
# No more than 500 workflow runs can de queue in a 10 second interval per repo

name: github users deploy workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version tag(master is required)'
        required: true
        default: 'v.0.0.1'
        type: string
    # prod 要加 tag 必填
    # tags:
    #     description: 'Version Tag'
    #     required: true
    #     type: string

  # push:
  #   branches:
  #     # change main to master
  #     - main
  #     # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags
  #     # will remove
      # - 'test/action/*'
  #     # Sequence of patterns matched against refs/tags
  #   # tags:
  #     # - release/**
  #     # # matches all version branching and tags with major version 1 or 2
  #     # - v[12].[0-9]+.[0.9]+
  # pull_request:
  #   branches: [main]

env:
  AWS_S3_BUCKET_PROD: prod
  AWS_S3_BUCKET_DEV: dev
  AWS_REGION: ap-northeast-1
  BUILD_FOLDER: build
  CLOUDFRONT_DEV_ID: dev1234
  CLOUDFRONT_PROD_ID: prod123

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set variable(short sha, branch name)
        #  set variable should give it a id
        id: customize-var
        # set short-sha = $(git rev-parse --short=8 HEAD)"
        run: |
          echo "::set-output name=short-sha::$(git rev-parse --short=8 HEAD)"
          echo "::set-output name=build-time::$(TZ=Asia/Taipei date +'%Y-%m-%dT%H:%M:%S%z')"
          echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
          echo "::set-output name=event-name::${GITHUB_EVENT_NAME}"
          echo "::set-output name=actor::${GITHUB_ACTOR}"
        # echo "::set-output name=version-tag::${github.event.inputs.version}"

      # can remove
      - name: Get variable(short sha, branch name)
        run: |
          echo "Short sha ${{steps.customize-var.outputs.short-sha}}"
          echo "branch ${{steps.customize-var.outputs.branch}}"
          echo "event name ${{steps.customize-var.outputs.event-name}}"
          echo "actor ${{steps.customize-var.outputs.actor}}"
          echo "version tag ${{github.event.inputs.version}"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      # 開發完成，最後再把註解拿掉
      - name: Test
        run: yarn test

      # done: 暫時註解
      # - name: Configure AWS credentials
      #   if: ${{steps.customize-var.outputs.branch == 'develop' || steps.customize-var.outputs.branch == 'main'}}
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{env.AWS_REGION}}

      # done: 暫時註解
      # - name: Configure AWS credentials
      #   if: ${{steps.customize-var.outputs.branch == 'develop' || steps.customize-var.outputs.branch == 'main'}}
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{env.AWS_REGION}}

      - name: Build dev static site
        if: ${{steps.customize-var.outputs.branch == 'test/action'}}
        run: yarn build:dev

      - name: Build prod static site
        if: ${{steps.customize-var.outputs.branch == 'main'}}
        run: yarn build

      # - useless
      # - name: Test tag name
      #   id: tag
      #   uses: actions/github-script@0.2.0
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #         return context.payload.ref.replace(/\/refs\/tags\//, '';
      - name: Echo tag name
        run: echo ${{ steps.tag.outputs.result }}

      # - name: Deploy static site to S3 bucket dev
      #   # change develop
      #   if: ${{steps.customize-var.outputs.branch == 'test/action'}}
      #   run: |
      #     aws s3 sync --delete./${BUILD_FOLDER} s3://$AWS_S3_BUCKET_DEV
      #     aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DEV_ID --paths "/*"

      # - name: Deploy static site to S3 bucket prod
      #   # change master
      #   if: ${{steps.customize-var.outputs.branch == 'main'}}
      #   run: |
      #     aws s3 sync --delete./${BUILD_FOLDER} s3://$AWS_S3_BUCKET_PROD
        # 手動點更新
        # aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_PROD_ID --paths "/*"

