# Bill
# https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#about-billing-for-github-actions
# work run time: each workflow run is limited 72 hours
# job queue time: limited 24 hours
# Api requests: execute up to 1000 API
# job matrix: can generate a maximum of 256 jobs per workflow run
# No more than 500 workflow runs can de queue in a 10 second interval per repo

name: github users deploy workflow

on:
  push:
    branches:
      # change main to master
      - main
      # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags
      # will remove
      - 'test/action/*'
      # Sequence of patterns matched against refs/tags
    # tags:
      # - release/**
      # # matches all version branching and tags with major version 1 or 2
      # - v[12].[0-9]+.[0.9]+
  pull_request:
    branches: [main]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get short sha
        id: custome-var
        run: |
          echo "::set-output name=short-sha::$(git rev-parse --short=8 HEAD)"