# Bill
# https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#about-billing-for-github-actions
# work run time: each workflow run is limited 72 hours
# job queue time: limited 24 hours
# Api requests: execute up to 1000 API
# job matrix: can generate a maximum of 256 jobs per workflow run
# No more than 500 workflow runs can de queue in a 10 second interval per repo

name: github users deploy workflow

on:
  push:
    branches:
      # change main to master
      - main
      # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags
      # will remove
      - 'test/action/*'
      # Sequence of patterns matched against refs/tags
    # tags:
      # - release/**
      # # matches all version branching and tags with major version 1 or 2
      # - v[12].[0-9]+.[0.9]+
  pull_request:
    branches: [main]

env:
  AWS_S3_BUCKET_PROD: 'prod'
  AWS_S3_BUCKET_DEV: 'dev'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set variable(short sha, branch name)
        #  set variable should give it a id
        id: customize-var
        # set short-sha = $(git rev-parse --short=8 HEAD)"
        run: |
          echo "::set-output name=short-sha::$(git rev-parse --short=8 HEAD)"
          echo "::set-output name=build-time::$(TZ=Asia/Taipei date +'%Y-%m-%dT%H:%M:%S%z')"
          echo "::set-output name=branch::${GITHUB_HEAD_REF}"

      # can remove
      - name: Get variable(short sha, branch name)
        run: |
          echo "Short sha ${{steps.customize-var.outputs.short-sha}},branch ${{steps.customize-var.outputs.branch}}"

      # 開發完成，最後再把註解拿掉
      # - name: testing
      #   if: ${{steps.customize-var.outputs.branch != 'main'}}
      #   run: yarn install && yarn test

      - name: Build dev static site
        # change develop
        if: ${{steps.customize-var.outputs.branch != 'main'}}
        run: |
          echo "s3 bucket name ${{env.AWS_S3_BUCKET_DEV}}"

      - name: Build prod static site
        if: ${{steps.customize-var.outputs.branch == 'main'}}
        run: |
          echo "s3 bucket name ${{env.AWS_S3_BUCKET_PROD}}"

